name: "CI"
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
  push:
    branches:
      - main
      - dev
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
      
jobs:
  call-dependency-review:
    if: github.event_name == 'pull_request'
    uses: m3im3i/actions-template/.github/workflows/depend-review-template.yaml@main
    with:
      self-hosted: false
      runner-labels: '[{"label": "ubuntu-latest"}]'
      language: 'csharp'
      fail-severity: 'critical'
      continue-on-err: true
  call-codeql:
    uses: m3im3i/actions-template/.github/workflows/codeql-template.yaml@main
    with:
      self-hosted: false
      runner-labels: '[{"label": "ubuntu-latest"}]'
      languages-torun: '[{"language": "csharp"}]'
    secrets: inherit
  call-unittest:
    uses: m3im3i/actions-template/.github/workflows/unittest-template.yaml@main
    with:
      self-hosted: false
      runner-labels: '[{"label": "ubuntu-latest"}]'
      language: 'csharp'
  call-build:
    # intentionally not to deploy is working on personal repo
    #if: ${{ !contains(github.repository, 'm3im3i') && github.event_name == 'push' }}
    if: ${{ github.event_name == 'push' }}
    needs: [call-codeql, call-unittest]
    uses: pcs-security/actions-template/.github/workflows/build-template.yaml@main
    with:
      self-hosted: false
      runner-labels: '[{"label": "ubuntu-latest"}]'
      language: 'csharp'
      image-name: ${{ github.repository }}/<dotnet-goat # for ghcr.io reg, set this var to ${{ github.repository }}/<image-name>
      environment-name: 'default'
    secrets:        
      reg_name: 'ghcr.io'
      reg_username: ${{ github.actor }}   
      reg_password: ${{ secrets.GITHUB_TOKEN }} 
  call-deploy: 
    # intentionally not to deploy is working on personal repo
    if: ${{ !contains(github.repository, 'm3im3i') && github.event_name == 'push' }}
    needs: [call-build]
    uses: pcs-security/actions-template/.github/workflows/deploy-template.yaml@main
    with:
      self-hosted: false
      runner-labels: '[{"label": "ubuntu-latest"}]'
      image-name: dotnet-goat #for ghcr.io reg, set this var to ${{ github.repository }}/<image-name>
      image-tag: 0.0.${{ github.run_number }}
      environment-name: 'AZURE_ENV'
      namespace: 'default'
    secrets:    
      reg_name: ${{ secrets.REGISTRY }}  
      reg_username: ${{ secrets.USERNAME }}      
      reg_password: ${{ secrets.PASSWORD }} 
      #reg_secret: ${{ secrets.IMAGE_PULL_SECRET }}
      kube_config: ${{ secrets.KUBE_CONFIG }} 
